version: 2
jobs:
  build:
    working_directory: ~/react-cypress-demo
    docker:
      - image: circleci/node:10.15.0
      - image: cypress/base:8

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

      # E2E using Cypress
      - run: 
          name: e2e
          command: npm start && cypress run

      # - run:
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
