version: 2
jobs:
  build:
    working_directory: ~/react-cypress-demo
    docker:
      - image: circleci/node:10.15.0
      - image: cypress/browsers:chrome67

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-npm-wee
          command: sudo npm install pm2 yarn -g

      - run:
          name: install-npm-wee
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

      # E2E using Cypress
      - run: 
          name: e2e
          command: pm2 start npm -- start && $(npm bin)/cypress

      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'

      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
